import 'dart:io';

import 'amiga_model.dart';
import 'emulator_settings.dart';
import 'file_category.dart';

/// Whether this platform can run the core's JIT at all.
///
/// Everywhere but iOS. Apple does not allow an app to make memory both
/// writable and executable, which is the whole mechanism -- so a config that
/// asks for one there does not run slowly, it runs into a core that cannot
/// honour the request. Android and Linux are fine.
///
/// Exposed rather than kept private so the UI can stop offering a switch that
/// could never do anything, instead of silently ignoring it.
bool get jitAvailable => !Platform.isIOS;

/// Turns settings into a .uae file.
///
/// Key names match cfgfile_save_options() in the core. The awkward parts are
/// commented where they are, because none of them are guessable from the key
/// name alone.
class ConfigGenerator {
  const ConfigGenerator._();

  /// Header the core writes on generated files.
  /// Must stay byte-identical to the core's expectation.
  static const String generatedByHeader = '; Generated by UAE4Arm Android UI';

  /// Config keys shared with the core's Android compatibility layer.
  static const String keyAndroidJoyport1 = 'amiberry.android_joyport1';
  static const String keyTouchSettingsVersion =
      'amiberry.touch_settings_version';
  static const String touchSettingsVersion = '1';
  static const String keyOnScreenJoystick = 'onscreen_joystick';
  static const String keyAmiberryOnScreenJoystick =
      'amiberry.onscreen_joystick';
  static const String keyOnScreenCd32Pad = 'onscreen_cd32pad';
  static const String keyAmiberryOnScreenCd32Pad = 'amiberry.onscreen_cd32pad';
  static const String keyVirtualKeyboardEnabled = 'vkbd_enabled';
  static const String keyDefaultOsk = 'input.default_osk';
  static const String keyShowAndroidKeyboardButton =
      'amiberry.show_android_keyboard_button';

  /// Whether a CD path is accepted at all. Deliberately the same narrow set
  /// the launcher used (FileCategory.cdImages): a .cue or .nrg is dropped
  /// rather than written into the config, matching shipping behaviour.
  static Set<String> get cdImageExtensions => FileCategory.cdImages.extensions;

  static String _cfg(bool value) => value ? 'true' : 'false';

  /// AmigaOS's IDE boot scan relies on an RDB (Rigid Disk Block) partition
  /// table. A raw hardfile without one can only auto-boot through UAE's own
  /// uaehf.device, never through emulated real IDE. Sniff the first 16 blocks
  /// for the RDSK magic to tell them apart.
  static bool hasRdbSignature(String path) {
    if (path.startsWith('content://')) {
      // Cannot cheaply sniff a content URI; assume a modern, RDB'd image.
      return true;
    }
    try {
      final RandomAccessFile file = File(path).openSync();
      try {
        final List<int> buffer = file.readSync(16 * 512);
        const List<int> magic = <int>[0x52, 0x44, 0x53, 0x4B]; // "RDSK"
        for (int offset = 0; offset + magic.length <= buffer.length; offset++) {
          bool matched = true;
          for (int i = 0; i < magic.length; i++) {
            if (buffer[offset + i] != magic[i]) {
              matched = false;
              break;
            }
          }
          if (matched) return true;
        }
        return false;
      } finally {
        file.closeSync();
      }
    } on Exception {
      // Unreadable: do not second-guess the default controller.
      return true;
    }
  }

  static String _normalizeCdImageValue(String value) {
    String normalized = value.trim();
    while (normalized.toLowerCase().endsWith(',image')) {
      normalized = normalized.substring(0, normalized.length - 6);
    }
    final String extension = normalized.contains('.')
        ? normalized.split('.').last.toLowerCase()
        : '';
    return cdImageExtensions.contains(extension) ? normalized : '';
  }

  static String _baseName(String path) {
    final List<String> parts = path.split(Platform.pathSeparator);
    return parts.isEmpty ? path : parts.last;
  }

  /// [isDirectoryPath] and [hasRdb] are injectable so tests can generate
  /// configs for paths that do not exist on the machine running them.
  /// The largest image the emulated A600/A1200/A4000 IDE controller can boot.
  ///
  /// The real hardware's IDE, and the OS 3.1 driver that talks to it, address
  /// a disk with 32 bits of BYTE offset -- so 4GB is the wall. Past it the
  /// drive mounts, reports nonsense geometry and boots nothing.
  static const int ideMaxImageBytes = 4 * 1024 * 1024 * 1024;

  static int _imageSize(String path) {
    if (path.startsWith('content://')) return 0;
    try {
      return File(path).lengthSync();
    } on FileSystemException {
      return 0;
    }
  }

  static String generate(
    EmulatorSettings settings, {
    bool Function(String path)? isDirectoryPath,
    bool Function(String path)? hasRdb,
    int Function(String path)? sizeOf,
  }) {
    final bool Function(String) isDir =
        isDirectoryPath ??
        (String path) =>
            !path.startsWith('content://') && Directory(path).existsSync();
    final bool Function(String) rdb = hasRdb ?? hasRdbSignature;
    final int Function(String) sizeOfImage = sizeOf ?? _imageSize;

    final StringBuffer out = StringBuffer();
    final String normalizedCdImage = _normalizeCdImageValue(settings.cdImage);
    final bool onScreenKeyboard = settings.onScreenKeyboard;
    final String androidJoyport1 = settings.joyport1;
    final String nativeJoyport1 = settings.joyport1 == 'onscreen_joy'
        ? 'joy1'
        : settings.joyport1;

    out.writeln(generatedByHeader);
    out.writeln();

    // CPU
    out.writeln('cpu_model=${settings.cpuModel}');
    // The one place that decides whether this machine gets a JIT.
    //
    // Written here rather than trusted from the settings because the settings
    // come from five different places -- the editor's switch, the wizard's
    // switch, the AGS setup, the collection recipes -- and every one of them
    // used to turn JIT on without asking which platform it was for. On iOS
    // that is not a slow config, it is an impossible one.
    final int jitCache = jitAvailable ? settings.jitCacheSize : 0;
    // "More compatible" together with JIT is a known-bad pairing: it forces
    // the slow exact instruction paths, so self-modifying code (WHDLoad ROM
    // decrypters and friends) runs orders of magnitude slower. The core only
    // auto-disables this for 68040+, so force it off for JIT'd 020/030 too.
    //
    // With no JIT the pairing does not arise, and cpu_compatible is what the
    // user asked for.
    final bool cpuCompatible = settings.cpuCompatible && jitCache == 0;
    out.writeln('cpu_compatible=${_cfg(cpuCompatible)}');
    out.writeln('cpu_24bit_addressing=${_cfg(settings.address24Bit)}');
    out.writeln('cpu_speed=${settings.cpuSpeed}');
    if (settings.fpuModel > 0) {
      out.writeln('fpu_model=${settings.fpuModel}');
    }
    if (jitCache > 0) {
      out.writeln('cachesize=$jitCache');
      out.writeln('compfpu=${_cfg(settings.jitFpu)}');
    }

    // Chipset
    out.writeln('chipset=${settings.chipset}');
    switch (settings.baseModel) {
      case AmigaModel.a600:
      case AmigaModel.a1200:
        out.writeln('ide=a600/a1200');
        break;
      case AmigaModel.a4000:
        out.writeln('ide=a4000');
        break;
      default:
        break;
    }
    out.writeln('immediate_blits=${_cfg(settings.immediateBlits)}');
    out.writeln('collision_level=${settings.collisionLevel}');
    out.writeln('cycle_exact=${_cfg(settings.cycleExact)}');
    out.writeln('ntsc=${_cfg(settings.ntsc)}');

    if (settings.baseModel == AmigaModel.cd32) {
      out.writeln('chipset_compatible=CD32');
      out.writeln('cd32cd=true');
      out.writeln('cd32c2p=true');
      out.writeln('cd32nvram=true');
      out.writeln('cdcon=cd32');
    } else if (settings.baseModel == AmigaModel.cdtv) {
      out.writeln('chipset_compatible=CDTV');
      out.writeln('cdtv=true');
      out.writeln('cdcon=cdtv');
    }

    // Memory
    out.writeln('chipmem_size=${settings.chipRam}');
    out.writeln('bogomem_size=${settings.slowRam}');
    out.writeln('fastmem_size=${settings.fastRam}');
    if (settings.z3Ram > 0) {
      out.writeln('z3mem_size=${settings.z3Ram}');
    }

    // RTG
    if (settings.useRtg) {
      out.writeln('gfxcard_type=ZorroIII');
      out.writeln('gfxcard_size=${settings.rtgMemory}');
      out.writeln('rtg_nocustom=true');
      out.writeln('rtg_noautomodes=false');
      out.writeln('gfx_fullscreen_picasso=fullwindow');
      if (settings.rtgTrueColour) {
        // Which pixel formats the card offers, as picasso96_modeflags.
        //
        // Left unset the card advertises a conservative set and Workbench
        // settles for 8- or 16-bit, which on a screen this size is visibly
        // banded. 0x3ffe is every format but NONE -- chunky through
        // A8R8G8B8 -- and is the value PiMiga's own working Amiberry config
        // uses, so it is a copy of something known to run rather than a
        // guess at a bitmask.
        out.writeln('rtg_modes=0x3ffe');
      }
    } else {
      out.writeln('gfxcard_size=0');
      out.writeln('rtg_nocustom=false');
    }

    // Kickstart
    if (settings.romFile.isNotEmpty) {
      out.writeln('kickstart_rom_file=${settings.romFile}');
    }
    if (settings.romExtFile.isNotEmpty) {
      out.writeln('kickstart_ext_rom_file=${settings.romExtFile}');
    }

    // Floppies
    if (settings.floppy0.isNotEmpty) out.writeln('floppy0=${settings.floppy0}');
    out.writeln('floppy0type=${settings.floppy0Type}');
    if (settings.floppy1.isNotEmpty) out.writeln('floppy1=${settings.floppy1}');
    out.writeln('floppy1type=${settings.floppy1Type}');
    if (settings.floppy2.isNotEmpty) out.writeln('floppy2=${settings.floppy2}');
    out.writeln('floppy2type=${settings.floppy2Type}');
    if (settings.floppy3.isNotEmpty) out.writeln('floppy3=${settings.floppy3}');
    out.writeln('floppy3type=${settings.floppy3Type}');
    final int numFloppies = settings.floppy3Type != -1
        ? 4
        : settings.floppy2Type != -1
        ? 3
        : settings.floppy1Type != -1
        ? 2
        : settings.floppy0Type != -1
        ? 1
        : 0;
    out.writeln('nr_floppies=$numFloppies');

    // CD
    if (normalizedCdImage.isNotEmpty) {
      // The ,image suffix is what makes the core mount it directly.
      out.writeln('cdimage0=$normalizedCdImage,image');
      out.writeln('cdimage0_present=true');
      out.writeln('cdimage0_readonly=true');
    } else if (settings.baseModel == AmigaModel.cd32 ||
        settings.baseModel == AmigaModel.cdtv) {
      // The CD consoles need this even with no disc, or the BIOS loops.
      out.writeln('cdimage0_present=false');
    }
    if (settings.baseModel == AmigaModel.cd32 && settings.cd32Fmv) {
      out.writeln('cd32fmv=true');
    }

    // WHDLoad
    if (settings.whdloadFilename.isNotEmpty) {
      out.writeln('whdload_filename=${settings.whdloadFilename}');
    }

    // Hard drives
    int physicalUnit = 0;
    bool bootPriSet = false;
    final int driveCount = settings.hardDrives
        .where((String d) => d.isNotEmpty)
        .length;
    // One image past the IDE's reach puts the WHOLE set on the UAE
    // controller, because the boot drive is the one that matters and mixing
    // controllers for a two-drive set buys nothing.
    //
    // This is what stops the big curated distributions booting. AmigaVision
    // is one 10GB image plus an 84MB saves drive; Zeb's WHDLoad pack is a
    // single 25GB image. Both are two drives or fewer, so both landed on the
    // emulated A1200 IDE and neither could boot -- while AGS, with twelve
    // drives, was pushed onto uaehf.device by the count alone and worked.
    // The size was never being asked about.
    final bool anyImageTooBigForIde = settings.hardDrives.any(
      (String path) =>
          path.isNotEmpty &&
          !isDir(path) &&
          sizeOfImage(path) >= ideMaxImageBytes,
    );
    for (int i = 0; i < settings.hardDrives.length; i++) {
      final String path = settings.hardDrives[i];
      if (path.isEmpty) continue;

      final String name = _baseName(path).isEmpty ? 'DH$i' : _baseName(path);
      // Only the first drive boots.
      final bool zebBootstrap =
          !bootPriSet && _baseName(path) == 'zeb-bootstrap';
      // Zeb's RDB also contains a bootable Workbench partition. Give the
      // bootstrap directory a clear priority so its Kickstart-copy script
      // runs first, then hands control to Zeb's own startup-sequence.
      final int bootPri = bootPriSet ? -128 : (zebBootstrap ? 10 : 0);
      bootPriSet = true;

      if (isDir(path)) {
        out.writeln('filesystem2=rw,DH$i:$name:"$path",$bootPri');
      } else {
        final bool rdbPresent = rdb(path);
        // The IDE controller on a real A600/A1200/A4000 has two units, and
        // the core models that. A set like AGS mounts ten drives, so past two
        // they go on the UAE controller, which has no such limit - which is
        // what a working AGS config does. Using ide for all of them produces a
        // machine that starts and never boots.
        final bool ideCapable =
            settings.baseModel == AmigaModel.a600 ||
            settings.baseModel == AmigaModel.a1200 ||
            settings.baseModel == AmigaModel.a4000;
        final bool useIde = rdbPresent &&
            ideCapable &&
            driveCount <= 2 &&
            !anyImageTooBigForIde;
        final String controller = useIde
            ? 'ide$physicalUnit'
            : 'uae$physicalUnit';
        // With an RDB the core detects geometry (0,0,0). Without one it needs
        // an explicit CHS to synthesise a bootable partition, otherwise the
        // mount fails with "no supported partition tables detected".
        final String geometry = rdbPresent ? '0,0,0' : '32,1,2';
        // The field after bootpri is the filesystem handler - a file the core
        // loads - not a device name. "uaehf.device" there sends it looking for
        // a handler that does not exist; the slot is meant to be empty for an
        // ordinary hardfile. Field order is
        // rw,DEV:path,sectors,surfaces,reserved,blocksize,bootpri,filesys,controller.
        out.writeln(
          'hardfile2=rw,DH$i:"$path",$geometry,512,$bootPri,,$controller',
        );
      }
      physicalUnit++;
    }

    // Sound
    out.writeln('sound_output=${settings.soundOutput}');
    out.writeln('sound_frequency=${settings.soundFreq}');
    out.writeln('sound_channels=${settings.soundChannels}');
    out.writeln('sound_stereo_separation=${settings.soundStereoSeparation}');
    out.writeln('sound_interpol=${settings.soundInterpolation}');

    // The emulated TCP/IP stack (bsdsocket.library over SLIRP) is compiled
    // out of the iOS core, so the guest has no network there; say so in the
    // config rather than asking for a library that does not exist.
    out.writeln('bsdsocket_emu=${Platform.isIOS ? 'false' : 'true'}');

    // Display
    final int activeWidth = settings.useRtg
        ? settings.rtgWidth
        : settings.gfxWidth;
    final int activeHeight = settings.useRtg
        ? settings.rtgHeight
        : settings.gfxHeight;
    out.writeln('gfx_width=$activeWidth');
    out.writeln('gfx_height=$activeHeight');
    out.writeln('gfx_fullscreen_amiga=fullwindow');
    // These are Amiberry host options, not WinUAE hardware options. The
    // target prefix is what routes them to target_parse_option(); without it
    // the core reports both lines as unknown and silently ignores the UI.
    out.writeln('amiberry.gfx_correct_aspect=${_cfg(settings.correctAspect)}');
    out.writeln('amiberry.gfx_auto_crop=${_cfg(settings.autoCrop)}');
    out.writeln('show_leds=${_cfg(settings.showLeds)}');

    // Input
    out.writeln('joyport0=${settings.joyport0}');
    out.writeln('joyport1=$nativeJoyport1');
    // A CD32 needs its control port explicitly in CD32-pad mode. Without this
    // the port stays a plain two-button Atari-style joystick, and CD32 titles
    // - which poll the pad's shift-register protocol for the coloured buttons
    // - see no usable controller at all, not merely fewer buttons.
    if (settings.baseModel == AmigaModel.cd32) {
      out.writeln('joyport1mode=cd32joy');
    }
    out.writeln('$keyAndroidJoyport1=$androidJoyport1');

    out.writeln('$keyTouchSettingsVersion=$touchSettingsVersion');

    // The host draws the controls, so the core must not draw its own.
    out.writeln('$keyOnScreenJoystick=false');
    out.writeln('$keyAmiberryOnScreenJoystick=false');
    out.writeln('$keyOnScreenCd32Pad=false');
    out.writeln('$keyAmiberryOnScreenCd32Pad=false');
    out.writeln('$keyVirtualKeyboardEnabled=false');
    out.writeln('$keyDefaultOsk=false');

    out.writeln('$keyShowAndroidKeyboardButton=${_cfg(onScreenKeyboard)}');

    // The host owns configuration; the core never opens a GUI of its own.
    out.writeln('use_gui=no');

    return out.toString();
  }
}
